
selector: textarea.comment-area

toolbar:
  - mybutton | codesample | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent
plugins:
  - codesample
  - autoresize
menubar: false
statusbar: false
width : 89%
autoresize_max_height: 1500


